Reddit/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resource :session
  resources :subs
  resources :posts do
    resources :comments, only: [:create]
  end
  resources :comments
end

Reddit/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Reddit/app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, :user_id, :post_id, presence: true

  belongs_to :author,
  foreign_key: :user_id,
  class_name: 'User'

  belongs_to :post

  belongs_to :parent,
  foreign_key: :parent_comment_id,
  class_name: 'Comment',
  optional: true

  # has_many :child_comments,
  # foreign_key: :parent_comment_id,
  # class_name: 'Comment',
  # optional: true

end

Reddit/app/models/post.rb
class Post < ApplicationRecord
  validates :title, :author, presence: true

  belongs_to :author,
  foreign_key: :user_id,
  class_name: 'User'

  has_many :post_subs, dependent: :destroy
  has_many :subs, through: :post_subs
  has_many :comments
end

Reddit/app/models/post_sub.rb
class PostSub < ApplicationRecord
  validates :post, :sub, presence: true

   belongs_to :sub
   belongs_to :post
end

Reddit/app/models/sub.rb
class Sub < ApplicationRecord
  validates :title, :moderator, presence: true

  belongs_to :moderator,
  foreign_key: :user_id,
  class_name: 'User'

  has_many :post_subs, dependent: :destroy
  has_many :posts, through: :post_subs

end

Reddit/app/models/user.rb
class User < ApplicationRecord
  validates :username, :password_digest, :session_token, presence: true
  validates :username, :session_token, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true}

  attr_reader :password
  after_initialize :ensure_session_token

  has_many :posts
  has_many :subs
  has_many :comments

  def self.find_by_credentials(username, password)
    @user = User.find_by(username: username)

    if @user && @user.is_password?(password)
      return @user
    else
      return nil
    end
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

Reddit/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :child_comments

  def current_user
    @current_user = User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def login(user)
    session[:session_token] = user.reset_session_token!
  end

  def ensure_login!
    redirect_to new_session_url unless logged_in?
  end

  def child_comments(comment)
    comments = Comment.all
    comments.select{|c| c.parent_comment_id == comment.id}
  end

end

Reddit/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :ensure_login!

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.post_id ||= params[:post_id]

    if @comment.save
      redirect_to post_url(@comment.post)
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to post_url(@comment.post)
    end

  end

  def show
    @comment = Comment.find(params[:id])
    # @comment.post_id = params[:post_id]
  end

  def comment_params
    params.require(:comment).permit(:content, :parent_comment_id, :post_id)
  end
end

Reddit/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :ensure_login!

  def new
    @post = Post.new
    @subs = Sub.all
    render :new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    if @post.save
      redirect_to post_url(@post)
    else
      @subs = Sub.all
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  # def destroy
  #   @post = current_user.posts.find(params[:id])
  #   @post.destroy!
  #   redirect_to sub_url(post.sub)
  # end

  def edit
    @post = current_user.posts.find(params[:id])
    @subs = Sub.all
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      @subs = Sub.all
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def show
    @post = current_user.posts.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end

end

Reddit/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password],
    )
    if @user
      login(@user)
      redirect_to subs_url
    else
      flash[:errors] = ["invalid credentials"]
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

Reddit/app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_action :ensure_login!

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = current_user.subs.find(params[:id])
  end

  def update
    @sub = current_user.subs.find(params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def sub_params
    params.require(:sub).permit(:title, :description)
  end

end

Reddit/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

Reddit/app/helpers/application_helper.rb
module ApplicationHelper
end

Reddit/app/views/comments/show.html.erb
<%= @comment.content %>

<br>

<h3>Reply to this comment</h3>

<form action=" <%= comments_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token  %>">
  <input type="hidden" name="comment[parent_comment_id]" value="<%= @comment.id %>">
  <input type="hidden" name="comment[post_id]" value="<%= @comment.post_id%>">
  <textarea name="comment[content]" rows="8" cols="80"></textarea>
  <br>
  <input type="submit" name="" value="Submit Comment">
</form>

Reddit/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if !logged_in? %>
      <li><a href="<%= new_session_url %>">Sign In!</a></li>
      <li><a href="<%= new_user_url %>">Sign Up!</a></li>
    <% else %>
      <ul>
        <%= current_user.username %>
        <li><a href="<%= new_sub_url %>"></a>Create a sub!</li>
        <li><a href="<%= subs_url %>"></a>All Subs</li>

          <form class="" action="<%= session_url %>" method="post">
              <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <input type="hidden" name="_method" value="delete">
            <input type="submit" name="" value="Sign Out!">
          </form>

      </ul>
    <% end %>

    <% flash.each do |er| %>
      <%= er  %>
    <% end %>

    <%= yield %>
  </body>
</html>

Reddit/app/views/posts/edit.html.erb
<h2>Edit Post!</h2>

<form class="" action="<%= post_url(@post) %>" method="post">
  <input type="hidden" name="_method" value="PATCH">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Title
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>

  <br>

  <label>URL
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label>

  <br>

  <label>Content
    <textarea name="post[content]" rows="4" cols="5"><%= @post.content %></textarea>
  </label>

  <br>

  <% @subs.each do |subby| %>
    <label>
      <input
        type="checkbox"
        name="post[sub_ids][]"
        value="<%= subby.id %>"
        <%= "checked" if @post.sub_ids.include?(subby.id) %> >
      <%= subby.title %>
      <br>
    </label>
  <% end %>

  <input type="submit" name="" value="Submit">
</form>

Reddit/app/views/posts/new.html.erb
<h2>New Post!</h2>

<form class="" action="<%= posts_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Title
    <input type="text" name="post[title]" value="">
  </label>

  <br>

  <label>URL
    <input type="text" name="post[url]" value="">
  </label>

  <br>

  <label>Content
    <textarea name="post[content]" rows="4" cols="5"></textarea>
  </label>

  <br>

  <% @subs.each do |subby| %>
    <label>
      <input type="checkbox" name="post[sub_ids][]" value="<%= subby.id %>">
      <%= subby.title %>
      <br>
    </label>
  <% end %>

  <input type="submit" name="" value="Submit">
</form>

Reddit/app/views/posts/show.html.erb
<h2><%= @post.title %></h2>by: <%= @post.author.username %>
<%= @post.url %>
<%= @post.content %>

<h3>Subs</h3>
<% @post.subs.each do |subby| %>
  <ul>
    <li><%= link_to subby.title, sub_url(subby) %></li>
  </ul>
<% end %>

<h3>Add Comment</h3>

<form action=" <%= post_comments_url(@post) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token  %>">
  <textarea name="comment[content]" rows="8" cols="80"></textarea>
  <br>
  <input type="submit" name="" value="Submit Comment">
</form>
<br>
<h1>Comments</h1>

<% @post.comments.each do |c| %>
  <ul>
  <li><%= link_to c.content, comment_url(c) %></li>
  <% child_comments(c).each do |ch| %>
    <%= ch.content %>
    <%= link_to c.content, comment_url(c) %> <br>
  </ul>
  <% end %>
<% end %>
<br>
<a href="<%= edit_post_url(@post) %>">Edit Post</a>

Reddit/app/views/subs/edit.html.erb
<h2>Edit sub!</h2>

<form class="" action="<%= sub_url(@sub) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Title
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>

  <label>Description
    <input type="textarea" name="sub[description]" value="<%= @sub.description %>">
  </label>

  <input type="submit" name="" value="Submit!">
</form>

Reddit/app/views/subs/index.html.erb
<h1>All the Subs!</h1>

<ul>
  <% @subs.each do |subby| %>
    <li><a href="<%= sub_url(subby) %>"><%= subby.title %></a></li>
    <br>
  <% end %>
</ul>

Reddit/app/views/subs/new.html.erb
<h2>Create a new sub!</h2>

<form class="" action="<%= subs_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Name
    <input type="text" name="sub[name]" value="">
  </label>

  <label>Description
    <input type="textarea" name="sub[description]" value="">
  </label>

  <input type="submit" name="" value="Submit!">
</form>

Reddit/app/views/subs/show.html.erb
<h1><%= @sub.title%></h1>

<h3>Description</h3>
<%= @sub.description %>

<%= link_to "Make New Post", new_post_url %>

<% @sub.posts.each do |post| %>
  <ul>
    <li><a href="<%= post_url(post) %>"><%= post.title %></a></li>
    <li><a href="<%= edit_sub_url(@sub) %>">Edit</a></li>
  </ul>
<% end %>

Reddit/app/views/users/new.html.erb
<h2>Sign Up</h2>

<form class="" action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Username
    <input type="text" name="user[username]" value="">
  </label>

  <label>Password
    <input type="password" name="user[password]" value="">
  </label>

  <input type="submit" name="" value="Sign Up!">
</form>